### ISSUE TITLE
关于模型功能的两个提问

### ISSUE THREAD

**Issue by tangzzz-fan** [LC1332/Zero-Haruhi#14]
开发者, 你好, 我有两个问题想要提问一下: 
1. 当前的模型选择的某个角色是否会具有从文本中学习的个性特色? 比如选择武林外传中的白展堂, 则后续的对话中, 这个聊天角色的个性是否会复合电视剧中人物的特色? 比如会在一些场景中说: 葵花点穴手; 遇到官府追查, 也会企图跑路? 如果有这方面的特征应用, 当前应用到什么程度了?
2. 第二种情况: 比如想要使用客户端(移动端/前端)调用模型的会话功能, 当前是否支持使用 API 调用, 比如使用 flask 包装, 支持 API 调用. 或者是否有计划对这部分进行支持?

非常感谢你的解答.

**Comment by LC1332** [comment]
这个特性是能够显现的 我从过往demo的一些历史记录里面也看到用户基本都能试出来； 第二条没有呢。 现在大家一般都封装成fastapi就是和openai那个接口一样形式去启服务，我最近在刷LIC2024别的比赛没空看这个。之后如果空下来打算进一步做多模态的尝试。
